// Some hosts (Render, and others that infer a start command before this
// repo had a build step) hardcode `node dist/index.js` as the run command,
// bypassing package.json's "main"/"start" entirely -- there's no way to fix
// that from inside the repo, only to make the path they hardcoded actually
// exist. tsc mirrors src/+examples/ under dist/ (dist/src/*.js), so the
// real compiled entry point is dist/src/index.js, not dist/index.js. This
// writes a tiny unconditional shim at the literal path such hosts expect,
// distinct from package.json's "main" (which correctly points library
// consumers at dist/src/index.js, with no unrequested side effects).
import { writeFileSync } from "node:fs";

writeFileSync(
  "dist/index.js",
  `// Auto-generated by scripts/postbuild.mjs -- do not edit.
// Deploy-entry shim for hosts that hardcode "node dist/index.js" as the
// start command. Always starts the HTTP server; library consumers should
// import "eral" (package.json "main" -> dist/src/index.js) instead, which
// has no import-time side effects.
import { startServer } from "./src/server.js";
startServer();
`,
);
